### ISSUE TITLE
在Github划水的时候在您的博客里转了一圈

### ISSUE THREAD

**Issue by AngelKitty** [Ainevsia/DailyCoding#1]
我稍微游走看了一下，发现您似乎也是学电气/电子相关的专业，握个小抓，都挺不容易的，感觉似乎挺住啊，不要放弃啊，乍一看似乎是一个pwn+密码学的师傅，TCTF开始的时候我还在北漂中ing，~~~~(>_<)~~~~
加油啊，保持微笑，继续走下去啊，开心过好每一天，希望您能走的更远！！！！

**Comment by Ainevsia** [comment]
......我才看到您的留言，真的是偶然用手机登github发现有一个closed的issue，不然真没机会看到。
这是本小白第一次收到鼓励啊，真的十分受宠若惊了，我默默关注您很久呢，从进入大学就开始关注您的博客了，谢谢您的鼓励。
虽然我现在真的很菜，心情也总是大起大落，但我不会忘记初心，少抱怨，多积累，希望有一天也能变得像您这样厉害。
再次感谢您的鼓励，收到您的issue我真的挺激动的，我的生活又多了一个强大的动力。当然也祝您考研顺利，实现自己的清华梦！

**Comment by AngelKitty** [comment]
> ......我才看到您的留言，真的是偶然用手机登github发现有一个closed的issue，不然真没机会看到。
> 这是本小白第一次收到鼓励啊，真的十分受宠若惊了，我默默关注您很久呢，从进入大学就开始关注您的博客了，谢谢您的鼓励。
> 虽然我现在真的很菜，心情也总是大起大落，但我不会忘记初心，少抱怨，多积累，希望有一天也能变得像您这样厉害。
> 再次感谢您的鼓励，收到您的issue我真的挺激动的，我的生活又多了一个强大的动力。当然也祝您考研顺利，实现自己的清华梦！

因为我看了你的一些感想，本来想找下联系方式的，你只留了个邮箱&GitHub。本人不才，觉得通过issue和你交流，有邮箱提醒应该能看到。本以为三天你都没有看到issue，觉得可能是你太忙了，没时间看吧，或者是消息太多了然后我的消息被冲下去了吧，各种猜想了一番，还是稍微有点小失落的。想想就把issue关掉吧，永远作为一个秘密，不便打扰到您。所以这事情也就搁一边了，我也没想到一个月后您竟然会回复我的消息，我也是备感荣幸，也很希望交到你这个朋友，如果不介意的话你可以邮件私信给我你的联系方式(WeChat or QQ or Telegram)
其次，真的非常感谢你的鼓励了，我看到了你很多优秀的一面，看到了一个作为一个交大的学生有的那股干劲，不抛弃不放弃的坚持，也有着自强不息，敢作敢当的的斗志和自信，你很厉害的，你一定能够实现你的梦想的，加油加油！！！
Best wishes to you！！！
